config/routes.rb
PimpMyMeme::Application.routes.draw do

  root :to => "memes#index"

  resources :memes, only: [:index, :create, :new, :show]
  resources :captions, only: [:create, :new]

end

app/models/Caption.rb
class Caption < ActiveRecord::Base
  attr_accessible :title, :meme_id, :signature, :body, :votes
  belongs_to :meme
  before_create :zero_votes

  def vote!
    self.update_attributes :votes => self.votes+1
  end

  private
  def zero_votes
    self.votes = 0
  end

end

app/models/Meme.rb
class Meme < ActiveRecord::Base
  attr_accessible :title, :image_url
  has_many :captions
  before_save :upload_photo


  private
  def upload_photo
    cloudinary = Cloudinary::Uploader.upload(params[:meme][:image_url])
    self.image_url = cloudinary["url"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/captions_controller.rb
class CaptionsController <ApplicationController
  def create
    @caption = Caption.new
  end

  def new
    @caption = Caption.new
  end

  def create
    @caption = Caption.create(params[:caption])

    render :partial => "/captions/newly_added", :locals => {:caption => @caption}
  end

  def update
    @caption = Caption.find(params[:id])
    @caption.votes +=1
    @caption.save
    render :partial => "/captions/newly_added", :locals => {:caption => @caption}
  end


end

app/controllers/memes_controller.rb
class MemesController < ApplicationController

  def index
    @memes = Meme.all
    @meme = Meme.new
  end

  def create
    clres = Cloudinary::Uploader.upload(params[:meme][:image_url])
    @meme = Meme.create(title: params[:meme][:title], image_url: clres["url"],
      public_id: clres["public_id"], height: clres["height"], width: clres["width"],
      format: clres["format"])
    redirect_to meme_path(@meme)
  end

  def new
    @meme = Meme.new
  end

  def show
    @meme = Meme.find(params[:id])
    @captions = @meme.captions.order("votes DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def voted_memes
    return cookies[:voted_memes].split('').map{|n| n.to_i} if cookies[:voted_memes]
    []
  end

  def voted_memes_add(meme_id)
    if cookies[:voted_memes] 
      cookies[:voted_memes] += @caption.meme_id.to_s
    else
      cookies[:voted_memes] = @caption.meme_id
    end
  end 
end

app/views/captions/_captions.html.erb
<table class="caption_table">

  <% @captions.each do |caption, votes| %>
  <tr><td><div class="vote_up"><button id ="<%=caption.id%>" class = "vote_up_button"></button><br><span class="vote_number"><%=caption.votes%></span></div></td><td><%= caption.title%></td><td>-<%=caption.signature%></td></tr>
  <% end %>
</table>

app/views/captions/_newly_added.html.erb
 <tr><td><div class="vote_up"><button id ="<%=caption.id%>" class = "vote_up_button"></button><br><span class="vote_number"><%=caption.votes%></span></div></td><td><%= caption.title%></td><td>-<%=caption.signature%></td></tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PimpMyMeme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/memes/_new.html.erb
<div class="new_meme">
<%= form_for @meme, method: "post" do |f| %>
<%= f.text_field :title, :placeholder => "Title your Meme" %><br>
<%= f.text_field :image_url, id:"meme_url", :placeholder => "Paste Image URL" %><br>
or
<div class="wrapper">
<%= f.file_field :image_url %>
</div>
<%= f.submit "submit" %>
<% end %>
</div>

  

app/views/memes/index.html.erb
// crazy big file, break it donw into partials.
<header>
  <h1 class="header">PIMP MY MEME</h1>
</header>

<div class="add-a-meme">
<%= link_to "+ add a meme", new_meme_path, class: "add-a-meme " %>
</div>

<div class="new">
  <div class="visible">
    <%= form_for @meme do |f| %>
      <%= f.text_field :title, :placeholder => "Title your Meme" %>
      <%= f.text_field :image_url, id: "meme_url", :placeholder => "Paste Image URL" %>
      or
      <div class="wrapper">
        <%= f.file_field :image_url %>
      </div>
      <%= f.submit "submit" %>
    <% end %>
  </div>
</div>



<% form_for :meme, url: memes_path(:meme) do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "submit" %>
<% end %>

<div class = "memes">
  <% @memes.shuffle.each do |meme|%>
    <%= link_to image_tag(meme.image_url, class:"meme", alt:meme.title), meme_path(meme) %>
  <%end %>
</div>

app/views/memes/new.html.erb
// indent!
<div class="new_meme">
<%= form_for @meme, method: "post" do |f| %>
  <%= f.text_field :title, :placeholder => "Title your Meme" %><br>
  <%= f.text_field :image_url, id:"meme_url", :placeholder => "Paste Image URL" %><br>
  or
  <div class="wrapper">
    <%= f.file_field :image_url %>
  </div>
  <%= f.submit "submit" %>
<% end %>
</div>

app/views/memes/show.html.erb
<div class="pimp_meme">
  <h1 class="meme"><a href='/' id="index">PIMP MY MEME</a></h1>
</div>
<div class="container">
<div class="meme" id="meme_box">

<div class="image" style='height="<%=@meme.height%>" width="<%=@meme.width%>"'>

  <div class="height-fix"><%=@meme.height%></div>
  <div class="width-fix"><%=@meme.width%></div>

  <%=cl_image_tag(@meme.public_id.concat("."+@meme.format), :crop => :limit, :width => 400, class:"meme_show", alt:@meme.title)%>
  <p class="image"><%if@captions.first%><%=@captions.first.title%><%end%></p>
</div>

</div>
<div class="caption_table">
<%= render "captions/captions" %>
</div>
<br>

<div class="caption_form">
  <%= form_for :caption do |f|  %>
  <%= f.text_area :title, :placeholder => "Show me your Meme"%><br>
  <%= f.text_field :signature, :placeholder => "Your Name" %><br>
  <%= f.hidden_field :meme_id, :value => @meme.id%>
  <%= f.submit "submit" %>
  <% end %>
</div>
</div>
<a class="vote_up_button">